### ISSUE TITLE
.gdbinit theme does not work out of the box, example?

### ISSUE THREAD

**Issue by dmikushin** [nojhan/colout#106]
I've copied example.gdbinit to ~/.gdbinit, but hooks do not have any effect on the newly opened gdb session. How to get colors working?

**Comment by nojhan** [comment]
Indeed, it's a bug on new versions of GDB (or a feature, depending on your
point of view, I guess).
I failed to find a workaround last time I checked (maybe related to
https://sourceware.org/bugzilla/show_bug.cgi?id=23135 ).
Help for the investigation would be welcomed.

**Comment by dmikushin** [comment]
Hi, what was the last good working version of GDB for you? Thanks!

**Comment by nojhan** [comment]
I don't know precisely, sorry.

Le lun. 2 sept. 2019 14:32, Dmitry Mikushin <notifications@github.com> a
écrit :

**Comment by nojhan** [comment]
Checked, it was a GDB regression. GDB 8.3 and 9.1 works well with the existing script in colout.
