### ISSUE TITLE
`-T` does not work with relative paths

### ISSUE THREAD

**Issue by FedericoStra** [nojhan/colout#114]
The source code is littered with `os.chdir` everywhere, and as a consequence `-T` does not work with relative paths because they are not interpreted w.r.t. the invocation directory, but the last directory `colout` happens to be in (most probably, something as `/home/<username>/.local/pipx/venvs/colout/lib/python3.11/site-packages/colout`).

**Comment by FedericoStra** [comment]
I see two alternatives.

- Never change directory during execution. This means that functions such as `load_themes` need to list files in a directory without `cd`ing into it. For instance,
https://github.com/nojhan/colout/blob/186dc04a86000e7c482b19012511233fb30e251e/colout/colout.py#L256
would become `glob.iglob(os.path.join(themes_dir, "colout_*.py"))`.
- Restore the previous directory after changing it. This can be accomplished manually (not recommended), or with a context manager, probably [`contextlib.chdir`](https://docs.python.org/3/library/contextlib.html#contextlib.chdir).

**Comment by nojhan** [comment]
While I would not qualify four occurrences as littering the code, it was definitely bad practice. I plead guilty, but I was young and ignorant.

Should be fixed with [1c07ace](https://github.com/nojhan/colout/commit/1c07ace0e2bd3ccfc4c9334b2c9fd0d7448bca42), thanks for the notice!
