### ISSUE TITLE
Update version on PyPI

### ISSUE THREAD

**Issue by agbuckley** [nojhan/colout#52]
Not really a code comment, but I just discovered colout and it looks awesome... so I tried installing it to test with pip. Which worked, but then I found that the output doesn't look like in the web page docs, some of the commands (for example using -P) don't work, etc. A bit surprising...

Looking on PyPI I see that the only version on there is 0.1, last updated in May, despite it being mentioned in the docs as one of the ways to get colout. It seems a lot has happened since then! Could a new version be uploaded to PyPI, please? Thanks!

**Comment by thedrow** [comment]
Version is now 0.4. This can be closed.
