### ISSUE TITLE
how to hightlight multiple strings like "foo" & "bar" at the same time

### ISSUE THREAD

**Issue by mintisan** [nojhan/colout#77]
I use,...
 
```
colout "foo"  red "bar" yellow
```

but it doesn't work.

how do I set commond?

**Comment by while0pass** [comment]
`somecommand_with_output_to_highlight | colout "foo" red | colout "bar" yellow`

**Comment by mintisan** [comment]
@while0pass 

oh, thank you, I forget "|" ....

**Comment by nojhan** [comment]
Passing through two pipes will take more CPU.
Thanks to regex groups, you can do it in one pass:
```colout "(foo).*(bar)" red,yellow```

**Comment by mintisan** [comment]
@nojhan 
3q for your geek way to do it.

And I think I should learn regex for doing my work in efficient way.

**Comment by nojhan** [comment]
Groups are really interesting for colout when you start playing with
colormaps (see the examples at the end of the readme).

**Comment by while0pass** [comment]
@nojhan I really like the way `colout` uses regex groups and colormaps, but your example `colout "(foo).*(bar)" red,yellow` is not very good when you need highlight totally unrelated patterns with different color or style throughout the output. The only way I'm aware of to do this is through chaning multiple colout invocations with pipes.

**Comment by nojhan** [comment]
Indeed.
