### ISSUE TITLE
Forwarding exit code

### ISSUE THREAD

**Issue by jimmyskull** [nojhan/colout#78]
I would like to obtain the exit code from a program execution. This would be useful for writing a pipeline of commands that a command depends on the success of the previous command.

Example:

`make | colout -t cmake && something that depends on the success of make`

**Comment by nojhan** [comment]
If you want pipes to forward errors, you should ask pipes, not commands ;-)

Commands like colout are not responsibles for such features, but your shell
is, just configure it with:
```set -o pipefail``` and you will get what you want.

You could also use parenthesis in your conditions, like: ```(make|colout)
&& make clean```

See also the example function at the end of the readme.

More useful info on: https://sipb.mit.edu/doc/safe-shell/
