### ISSUE TITLE
Make a new release?

### ISSUE THREAD

**Issue by blastrock** [nojhan/colout#79]
Hi,

It's been almost two years since the last release, could it be time to make a new one with the current master?

**Comment by nojhan** [comment]
We're close to reach 0.6 on the develop branch, maybe you could test it a bit?

**Comment by blastrock** [comment]
I've been using the develop branch for the past week, it seems to work as expected for my usage of cmake and ninja.

I still find it weird that make has its coloration included in the cmake theme whereas ninja's coloration is not, but it works.

**Comment by nojhan** [comment]
That's a good point, would you volunteer for dissociating cmake and make themes in two different files before the release or should I release first?

**Comment by blastrock** [comment]
Sorry, I don't have much free time currently. I would recommend releasing without and making another release when that split is done. It's not that important anyway :)

**Comment by nojhan** [comment]
v0.6.1 pushed today
