### ISSUE TITLE
Pypi package for 0.4 is different from Github tag v0.4

### ISSUE THREAD

**Issue by Louis-Kenzo** [nojhan/colout#80]
One consequence is that some bugs fixed on Github's v0.4 tag are not fixed on Pypi (e.g. [UnicodeDecodeError](https://github.com/nojhan/colout/commit/6092addb10828b0f978bc3a495f78a3e77cd4b96)).

```
v=0.4
gh_url=https://codeload.github.com/nojhan/colout/zip/v$v
pp_url=https://pypi.python.org/packages/source/c/colout/colout-$v.tar.gz
curl -s $gh_url -o /tmp/$v.gh.zip
curl -s $pp_url -o /tmp/$v.pp.tar.gz
unzip -qo /tmp/$v.gh.zip -d /tmp/$v.gh
mkdir -p /tmp/$v.pp && tar xf /tmp/$v.pp.tar.gz -C /tmp/$v.pp
diff -r /tmp/$v.{gh,pp} -y --suppress-common-lines
```

**Comment by carlwgeorge** [comment]
Since the last tag was in 2014, how about a new release as a work around?

**Comment by nojhan** [comment]
I'm not the PyPi package manager… but I will tag a release, just in case.

**Comment by nojhan** [comment]
Just released the 0.5 version. Hope the package maintainer is still motivated.

**Comment by carlwgeorge** [comment]
I used the tag tarball to create an [Arch Package in the AUR](https://aur.archlinux.org/packages/colout/).  If it gets uploaded to PyPI I can switch the source to that tarball, but this is fine for now.  Thanks!

**Comment by diogocp** [comment]
@dongweiming are you the PyPI package maintainer? Could you please update the package or make @nojhan the maintainer?

**Comment by dongweiming** [comment]
@nojhan what's your PyPI username? I want to add you to the owner list, then transfer to you

**Comment by dongweiming** [comment]
@Louis-Kenzo @carlwgeorge @diogocp I'm very sorry for this. i had upload the 0.5 version to PYPI. and i will transfer this package to @nojhan
