### ISSUE TITLE
Confusing -r / --resources behaviour

### ISSUE THREAD

**Issue by smileart** [nojhan/colout#81]
When one try to use `-r` or `--resources` flag to list all the colours and stuff, colout throws an error:

``` bash
colout.py: error: too few arguments
```

Which is quite confusing. To see the list you have to add anything else to the command, like:

``` bash
colout abc -r
```

Maybe I'm wrong, but it sounds like an issue or at least a pretty queer behaviour 🤔

**Comment by nojhan** [comment]
True. The documented recommendation is `colout -r RESOURCE`, with RESOURCE being the section you want to see (any string would fall back to `all`), but there is no support for an empty string, indeed. It's mainly because I failed to find an elegant design to handle it.

**Comment by nojhan** [comment]
Still no idea how to fix this, bailing out.

**Comment by tomasohara** [comment]
Can you re-open this bug. A quick fix is shown at the end.

Note that it is confusing because the usage indicates that *-r* is a flag:
```
$ colout -r
usage: colout [-h] [-g] [-c] [-l SCALE] [-a] [-t] [-T DIR] [-P DIR] [-d COLORMAP] [-r] [-s]
              [-e CHAR] [-E CHAR] [--debug]
              REGEX [COLOR] [STYLE]
colout: error: the following arguments are required: REGEX
```
Additional support comes from the [documentation tips](http://nojhan.github.io/colout):

> **colout -r** will give you the lists of available colors, colormaps, themes and supported programming languages.

A simple fix is to append "ALL" to the system command line if it just contains -r or --resources:

```
 git diff | cat
diff --git a/colout/colout.py b/colout/colout.py
index 85ed7b0..58368c7 100755
--- a/colout/colout.py
+++ b/colout/colout.py
@@ -889,6 +889,12 @@ def _args_parse(argv, usage=""):
     parser.add_argument("--debug", action="store_true",
             help="Debug mode: print what's going on internally, useful if you want to check what features are available.")
 
+    # Mock up "--resources ALL" if just "--resources" on command line
+    if (len(sys.argv) == 2 and (sys.argv[1] in ["-r", "--resources"])):
+        sys.argv.append("ALL")
+        ## NOTE: FOllowing leads to warning about syntax coloring not being available
+        ## TODO: logging.debug(f"Added ALL to argv: {sys.argv}\n")
+
     args = parser.parse_args()
 
     return args.pattern[0], args.color, args.style, args.groups, \

```

**Comment by tomasohara** [comment]
Can you re-open this bug? A quick fix is shown at the end.

Note that it is confusing because the usage indicates that -r is a flag:
```
$ colout -r
usage: colout [-h] [-g] [-c] [-l SCALE] [-a] [-t] [-T DIR] [-P DIR] [-d COLORMAP] [-r] [-s]
              [-e CHAR] [-E CHAR] [--debug]
              REGEX [COLOR] [STYLE]
colout: error: the following arguments are required: REGEX
```
Additional support comes from the [documentation tips](http://nojhan.github.io/colout):

> colout -r will give you the lists of available colors, colormaps, themes and supported programming languages.

A simple fix is to append "ALL" to the system command line if it just contains -r or --resources:

```
$ git diff | cat
diff --git a/colout/colout.py b/colout/colout.py
index 85ed7b0..58368c7 100755
--- a/colout/colout.py
+++ b/colout/colout.py
@@ -889,6 +889,12 @@ def _args_parse(argv, usage=""):
     parser.add_argument("--debug", action="store_true",
             help="Debug mode: print what's going on internally, useful if you want to check what features are available.")
 
+    # Mock up "--resources ALL" if just "--resources" on command line
+    if (len(sys.argv) == 2 and (sys.argv[1] in ["-r", "--resources"])):
+        sys.argv.append("ALL")
+        ## NOTE: FOllowing leads to warning about syntax coloring not being available
+        ## TODO: logging.debug(f"Added ALL to argv: {sys.argv}\n")
+
     args = parser.parse_args()
 
     return args.pattern[0], args.color, args.style, args.groups, \
```

**Comment by tomasohara** [comment]
That's OK, but thanks for checking. If I make a more substantial contribution in the future, I'll add a pull request.
