### ISSUE TITLE
Does `tail -f | grep -v | colout` work?

### ISSUE THREAD

**Issue by djkeh** [nojhan/colout#82]
I tried applying a command line to the apache acces log file like this:

```sh
tail -f $1 | grep -v "test.html" | colout "(^[0-9\.]+)|(\([0-9\.]+\))|([\[\]])|(\:)|([0-9])|(GET|POST|DELETE)" green,blue,cyan,magenta,purple,orange
```

In this command regex looks complicated but it's not the point so please don't mind.
With this pipe command I'd like to keep monitoring access logs which filtered "test.html" out, with beautifully colorized output.
However, this command seems not working, shows just nothing.
Could you tell what's wrong with the command?

**Comment by nojhan** [comment]
Without more information, I would say it's most probably a buffering problem. Try using stdbuf (in coreutils) or change your shell configuration.

Else, please give a minimal _working_ example.

**Comment by nojhan** [comment]
I've tested and `stdbuf` indeed solve your problem: `tail -f $1 | stdbuf -o0 grep -v X | colout X`.
I've updated the README with this hint in f03ed7a.
