### ISSUE TITLE
Allow for a different color list separator

### ISSUE THREAD

**Issue by nkh** [nojhan/colout#83]
',' can confuse some tools, IE fzf --bind command

**Comment by nojhan** [comment]
Can you give a minimal working example of the problem, please?

**Comment by nkh** [comment]
here is the fzf command line I had problems with. I do not mean that the problem is with your sofware but that an alternate delimiter could be nice

fzf --read0 --no-sort -m --ansi --preview-window down:50% --no-hscroll 
--preview "echo {} | colout '(NAME)*(DESCRIPTION)*(LONG_)*(DEFINED_AT)*' red,blue,blue,blue " --bind "ctrl-v:execute(printf {} | colout '(NAME)' red | colout '(DESCRIPTION)*(LONG_)*(DEFINED_AT)*' blue 

You can see that when colout is used, in the preview option, I have to pipe twice; I can't liste the colors separated by a comma as it make fzf, or some shell parsinf fail

**Comment by nojhan** [comment]
Added an option to change the separator in 881a2c7cbd53637aa51d941697ac0a0e09ee8c44 (but bug #92 is still on the way).

**Comment by nojhan** [comment]
Added with the `-e`/`--sep-list` option (working after 4b758a5f9e92fc70d4c646657f05a0ab9f22b053).

Example: `echo "pim pam poum"|cpy colout -e / -c p red/blue`
