### ISSUE TITLE
Installation does not work with pip

### ISSUE THREAD

**Issue by kecsap** [nojhan/colout#99]
If I try to install colout with pip2 or pip3 in Ubuntu 18.04, I get the following:

pip2 install --user colout

Collecting colout
  Using cached https://files.pythonhosted.org/packages/3d/ba/3ef31c0df3ace69271cc8b1af6b529f24de66ff42c0d99a8d18aa980a307/colout-0.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-Sbxx_G/colout/setup.py", line 25, in <module>
        long_description=open('README.md').read(),
    IOError: [Errno 2] No such file or directory: 'README.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-Sbxx_G/colout/

**Comment by Code0x58** [comment]
#98 fixes this and other issues.

You can currently install it with `PIP_INDEX_URL=https://test.pypi.org/simple pip install --user colout`, but be aware that you will probably have to uninstall it and install the one from the main pypi once a release is made (in case the version number is behind.

**Comment by nojhan** [comment]
And the release was made.
